services:
  - type: web
    name: tagcheck-viewer
    runtime: static
    buildCommand: ''
    staticPublishPath: .
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
